// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Product",
    checkConstraints: {
      Product_xata_id_length_xata_id: {
        name: "Product_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_Product_xata_id_key: {
        name: "_pgroll_new_Product_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "name",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "price",
        type: "float",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "status",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: "'In stock'::text",
        comment: "",
      },
      {
        name: "stock",
        type: "int",
        notNull: false,
        unique: false,
        defaultValue: "10",
        comment: "",
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Product = InferredTypes["Product"];
export type ProductRecord = Product & XataRecord;

export type DatabaseSchema = {
  Product: ProductRecord;
};

const DatabaseClient = buildClient();

// Load environment variables
const apiKey = import.meta.env.XATA_API_KEY ?? process.env.XATA_API_KEY;
const dbURL = "https://An-s-workspace-k8uaf8.us-east-1.xata.sh/db/hairstyling";
const branch = import.meta.env.XATA_BRANCH ?? process.env.XATA_BRANCH ?? "main";

if (!apiKey) {
  throw new Error(
    "XATA_API_KEY is not defined. Please set it in your environment variables."
  );
}

const defaultOptions = {
  databaseURL: dbURL,
  branch: branch,
  apiKey: apiKey,
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
